services:
  - type: web
    name: auditoria-backend
    env: docker
    plan: free
    dockerfilePath: Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: "false"
      - key: APP_NAME
        value: AuditoriaBackend
      - key: DB_CONNECTION
        value: pgsql
      - key: DB_HOST
        value: aws-0-us-east-1.pooler.supabase.com
      - key: DB_PORT
        value: "5432"
      - key: DB_DATABASE
        value: postgres
      - key: DB_USERNAME
        value: postgres.nyyectlztumysnvurttc
      - key: DB_PASSWORD
        value: AUDITORIAjUL32
      - key: CACHE_STORE
        value: file
      - key: SESSION_DRIVER
        value: file
      - key: RUN_MIGRATIONS
        value: "true"
